Repository CodeHanZoom/greenwalk_android, pull requests merged in 2024-05, with the labels that each got.

#29 [Fix] Unresolved reference: Logo
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/codehanzoom/greenwalk/api/ApiClient.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/HomeScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/LoginScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/StartScreen.kt
Labels: 환경설정, 오류수정

#33 [Feat] 걸음수, 이동거리, 지도 API 구현
  .idea/deploymentTargetDropDown.xml
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codehanzoom/greenwalk/MainActivity.kt
  app/src/main/java/com/codehanzoom/greenwalk/api/SensorClient.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/GetDistance.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/GetStep.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/GetTIme.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/Logo.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/NavigationGraph.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/MapScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/PloggingScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/RecordScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/PloggingViewModel.kt
  build.gradle.kts
  settings.gradle.kts
Labels: 기능구현, 환경설정, 퍼블리싱

#40 [Feat] ViewModel 도입 및 screen 별 반영
  app/src/main/java/com/codehanzoom/greenwalk/model/PloggingModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/Camera.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/RetrofitClient.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/UploadService.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/getGrade.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/HomeScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/PointScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/PloggingInfoViewModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/UserInfoViewModel.kt
Labels: 기능구현, 오류수정

#42 [Design] 마이페이지 퍼블리싱
  app/src/main/java/com/codehanzoom/greenwalk/api/UserService.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/DonationListArea.kt
  app/src/main/java/com/codehanzoom/greenwalk/model/DonationModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/MypageScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/MyPageViewModel.kt
  app/src/main/res/drawable/ic_account_circle.png
Labels: 기능구현, 퍼블리싱

#45 [Feat] 카메라 촬영 후 동작 변경
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/codehanzoom/greenwalk/CameraScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/model/UserInfoModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/Camera.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/HomeScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/UserInfoViewModel.kt
Labels: 기능구현

#47 [Design] 디자인 수정
  app/src/main/java/com/codehanzoom/greenwalk/compose/AttendanceArea.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/LargeButton.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/MaxWidthButton.kt
  app/src/main/java/com/codehanzoom/greenwalk/model/DonationModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/model/UserInfoModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/BottomNavItem.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/NavigationGraph.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/GetDistance.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/GetStep.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/GetTIme.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/convertMetersToKilometers.kt
  app/src/main/java/com/codehanzoom/greenwalk/utils/getGrade.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/HomeScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/LoginScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/MarketScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/MypageScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/NewsfeedScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/PartnerScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/PloggingScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/PointScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/RecordScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/SignUpScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/LoginViewModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/UserInfoViewModel.kt
  app/src/main/res/drawable/image_greenwalk.png
  app/src/main/res/drawable/logo_greenwalk.png
  app/src/main/res/drawable/logo_greenwalk_small.png
Labels: 기능구현, 리팩터링, 퍼블리싱

#49 [Design] 기부처 리스트 아이콘 추가, 스플래시 디자인 변경
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codehanzoom/greenwalk/MainActivity.kt
  app/src/main/java/com/codehanzoom/greenwalk/model/PartnersModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/NavigationGraph.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/PartnerScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/SplashScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/StartScreen.kt
  app/src/main/res/values/themes.xml
Labels: 기능구현, 리팩터링, 퍼블리싱
