Repository CodeHanZoom/greenwalk_android, pull requests merged in 2024-04, with the labels that each got.

#21 [Design] 플로깅 페이지 퍼블리싱
  app/src/main/java/com/codehanzoom/greenwalk/HomeScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/Main.kt
  app/src/main/java/com/codehanzoom/greenwalk/PloggingScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/NavigationGraph.kt
  app/src/main/res/drawable-nodpi/pic_test_map.png
  app/src/main/res/drawable/ic_home.png
  app/src/main/res/drawable/ic_market.png
  app/src/main/res/drawable/ic_newsfeed.png
Labels: 리팩터링, 퍼블리싱

#23 [Feat] API 연둥 및 화면간의 라우트 연결 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codehanzoom/greenwalk/Main.kt
  app/src/main/java/com/codehanzoom/greenwalk/MainActivity.kt
  app/src/main/java/com/codehanzoom/greenwalk/api/ApiClient.kt
  app/src/main/java/com/codehanzoom/greenwalk/api/ApiService.kt
  app/src/main/java/com/codehanzoom/greenwalk/api/SharedPreferencesManager.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/LargeButton.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/MaxWidthButton.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/SmallButton.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/TopBar.kt
  app/src/main/java/com/codehanzoom/greenwalk/model/LoginModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/model/SignUpModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/BottomNavItem.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/NavigationGraph.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/HomeScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/LoginScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/MarketScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/MypageScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/NewsfeedScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/PloggingScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/RecordScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/SignUpScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/LoginViewModel.kt
  app/src/main/java/com/codehanzoom/greenwalk/viewModel/SignupViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 기능구현, 리팩터링, 환경설정, 퍼블리싱

#25 [Design] 스플래시 스크린 기능구현 및 시작하기 스크린 퍼블리싱
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codehanzoom/greenwalk/Main.kt
  app/src/main/java/com/codehanzoom/greenwalk/MainActivity.kt
  app/src/main/java/com/codehanzoom/greenwalk/RegisterActivity.kt
  app/src/main/java/com/codehanzoom/greenwalk/compose/LargeButton.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/BottomNavItem.kt
  app/src/main/java/com/codehanzoom/greenwalk/nav/NavigationGraph.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/HomeScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/LoginScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/RecordScreen.kt
  app/src/main/java/com/codehanzoom/greenwalk/view/StartScreen.kt
  app/src/main/res/drawable-nodpi/ic_plogging_complete.png
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_mypage.png
  app/src/main/res/drawable/ic_plogging_clear.xml
  app/src/main/res/drawable/img_splash.jpeg
  app/src/main/res/drawable/notification_picture.png
  app/src/main/res/values/themes.xml
Labels: 기능구현, 리팩터링, 퍼블리싱
